from ._decorators import glyph_method as glyph_method
from ._figure import Figure as Figure
from bokeh.models import ColumnDataSource
from bokeh.models.renderers import GlyphRenderer as GlyphRenderer
from typing import Any, Sequence

class BokehAccessor(Figure):
    def __init__(self, df) -> None: ...
    def __call__(self, *args, **kwargs) -> BokehAccessor: ...
    def annular_wedge(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def annulus(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def arc(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def block(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def ellipse(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def image(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def image_rgba(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def image_stack(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def image_url(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def line(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def mathml_glyph(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def ngon(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def patch(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def ray(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def rect(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def scatter(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def step(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def tex_glyph(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def text(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def wedge(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def varea(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def varea_step(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def vbar(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def vspan(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def harea(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def harea_step(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def hbar(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def hspan(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def bezier(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def hstrip(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def hextile(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def multi_line(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def multipolygons(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def patches(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def quad(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def quadratic(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def segment(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def vstrip(self, *args: Any, **kwargs: Any) -> GlyphRenderer: ...
    def harea_stack(self, stackers: Sequence[str], **kwargs: Any) -> list[GlyphRenderer]: ...
    def hbar_stack(self, stackers: Sequence[str], **kwargs: Any) -> list[GlyphRenderer]: ...
    def hline_stack(self, stackers: Sequence[str], **kwargs: Any) -> list[GlyphRenderer]: ...
    def varea_stack(self, stackers: Sequence[str], **kwargs: Any) -> list[GlyphRenderer]: ...
    def vbar_stack(self, stackers: Sequence[str], **kwargs: Any) -> list[GlyphRenderer]: ...
    def vline_stack(self, stackers: Sequence[str], **kwargs: Any) -> list[GlyphRenderer]: ...

class PolarsBokehAccessor(BokehAccessor):
    __view_model__: str
    __view_module__: str
    @property
    def source(self) -> ColumnDataSource: ...

class PandasBokehAccessor(BokehAccessor):
    __view_model__: str
    __view_module__: str
    @property
    def source(self) -> ColumnDataSource: ...
