from typing import Any


class _BokehAccessor:
    def glyph(self, *args: Any, **kwargs: Any) -> Any: ...
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...
    def accepted_figure_kwargs(self, *args: Any, **kwargs: Any) -> Any: ...
    def accepted_glyph_kwargs(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...


class DataFrame:
    bokeh: _BokehAccessor

    def __getattr__(self, name: str) -> Any: ...
