import polars as pl

class QuantAccessor:
    def __init__(self, expr: pl.Expr) -> None: ...
    def returns(self, periods: int = 1, over: str | None = None) -> pl.Expr: ...
    def compound(self, over: str | None = None) -> pl.Expr: ...
    def rolling_vol(self, window_size: int, weights: list[float] | None = None, *, min_samples: int | None = None, center: bool = False, ddof: int = 1, over: str | None = None) -> pl.Expr: ...
    def rolling_beta(self, benchmark_col: pl.Expr, window_size: int, min_periods: int | None = None, ddof: int = 1, over: str | list[str] | None = None) -> pl.Expr: ...
